<?
$css_version = 'ver=1.1.8'; // Версия CSS файлов
$js_version = 'ver=1.0.6'; // Версия js файлов
$hierarchy = umiObjectsCollection::getInstance();
switch ($variables['@lang-id']) {
  case '1':
    $obj = $hierarchy->getObject(667);
    break;
  case '2':
    $obj = $hierarchy->getObject(671);
    break;
  case '3':
    $obj = $hierarchy->getObject(668);
    break;
  default:
    # code...
    break;
}
?>
<!DOCTYPE html>
<html lang="ru">
<head>

  <meta charset="UTF-8">
  <meta name="description" content="KSU">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta property="og:image" content="path/to/image.jpg">
  <meta name="theme-color" content="#009ee0">
  <title>КГУ им.А.Байтурсынова</title>
  <link rel="icon" href="/templates/ksu/img/favicon/favicon.ico">
  <link rel="stylesheet" href="/templates/ksu/libs/bootstrap-grid/dist/bootstrap-grid.min.css">
  <link rel="stylesheet" href="/templates/ksu/libs/fancybox/jquery.fancybox.min.css">
  <link rel="stylesheet" href="/templates/ksu/libs/owl-carousel/owl.carousel.min.css">
  <link rel="stylesheet" href="/templates/ksu/libs/owl-carousel/owl.theme.default.min.css">
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Montserrat:500,900&display=swap">
  <link rel="stylesheet" href="/templates/ksu/css/old.css?<?echo $css_version?>">
  <link rel="stylesheet" href="/templates/ksu/css/main.min.css?<?echo $css_version?>">
  <link rel="stylesheet" href="/templates/ksu/css/temp.min.css?<?echo $css_version?>">
  <?
    switch ($variables['@domain']) {
      case 'ati.ksu.edu.kz':
        echo '<link rel="stylesheet" href="/templates/ksu/css/ati.min.css?'.$css_version.'">';
        break;
      case 'iel.ksu.edu.kz':
        echo '<link rel="stylesheet" href="/templates/ksu/css/iel.min.css?'.$css_version.'">';
        break;
      case 'idl.ksu.edu.kz':
        echo '<link rel="stylesheet" href="/templates/ksu/css/idl.min.css?'.$css_version.'">';
        break;

      default:
        # code...
        break;
    }
  ?>

</head>
<body>
