<? include "lang/langselect.phtml"; ?>
<? include "include/head.phtml"; ?>
<header class="header">
	<div class="container">
		<? include 'top-header.phtml' ?>
		<div class="content">
			<div class="content__title">
				<span><? print_r($obj->getValue('header-content-title')); ?></span>
			</div>
			<?
			switch ($variables['@domain']) {
				case 'ksu.edu.kz':
					echo '
					<div class="header-news">
						<div class="header-news__ticker">
							<ul id="webTicker">
							'. $this->render($this->macros('news', 'lastlist', array('newslist', null, null, true)), 'news/lastlist').'
							</ul>
						</div>
						'.$this->render($this->macros('news', 'lastlist', array('newslist', null, null, true)), 'news/rightoplist').'
					</div>';
					break;
				default:
					echo '';
					break;
			}
			?>
		</div>
	</div>
</header>
<div class="container">
	<marquee class="marquee" behavior="scroll" direction="left"><a href="http://md.ksu.edu.kz">16.03.2020 года, в связи с пандемией коронавируса, КГУ им. А. Байтурсынова перешел на дистанционною систему обучения</a></marquee>
</div>
<section id="menu">
	<div class="container">
		<div class="row">
			<div class="col-lg-3 col-md-3 col-sm-6 col-6">
				<div class="stud-nav stud-nav_student">
					<a class="stud-nav__link" href="/<?= urlencode($variables['@lang']); ?>/4block/distance_learning/">
						<div class="stud-nav__title"><?= $dot ?></div>
					</a>
				</div>
			</div>

			<div class="col-lg-3 col-md-3 col-sm-6 col-6">
				<div class="stud-nav stud-nav_abb">
					<a class="stud-nav__link" href="/<?= urlencode($variables['@lang']); ?>/4block/abiturientu/">
						<div class="stud-nav__title"><?= $abitur ?></div>
					</a>
				</div>
			</div>
			<div class="col-lg-3 col-md-3 col-sm-6 col-6">
				<div class="stud-nav stud-nav_voen">
					<a class="stud-nav__link" href="/<?= urlencode($variables['@lang']); ?>/4block/voennaya-kafedra/">
						<div class="stud-nav__title"><?= $voennaya ?></div>
					</a>
				</div>
			</div>

			<div class="col-lg-3 col-md-3 col-sm-6 col-6">
				<div class="stud-nav stud-nav_grant">
					<a class="stud-nav__link" href="/<?= urlencode($variables['@lang']); ?>/4block/granty-i-skidki/">
						<div class="stud-nav__title"><?= $grant ?></div>
					</a>
				</div>
			</div>
			<!--div class="col-lg-3 col-md-3 col-sm-6 col-6">
				<div class="stud-nav stud-nav_student">
					<a class="stud-nav__link" href="/<?= urlencode($variables['@lang']); ?>/4block/nashi-vypuskniki/">
						<div class="stud-nav__title"><?= $our ?></div>
					</a>
				</div>
			</div-->
		</div>
		<div class="content-nav">
		<div class="row">
			<div class="col-lg-3 col-md-6 col-sm-6">
				<a href="http://acportal.ksu.edu.kz/" target="_blank" class="content-nav__item">
					<?= $anti_portal ?>
					<img src="/templates/ksu/img/icons/header/portal.svg" alt="Портал">
				</a>
			</div>
			<div class="col-lg-3 col-md-6 col-sm-6">
				<a href="http://ksu.edu.kz/timetable/" class="content-nav__item">
					<?= $blocktimetable ?>
					<img src="/templates/ksu/img/icons/header/portal.svg" alt="Портал">
				</a>
			</div>
			<div class="col-lg-3 col-md-6 col-sm-6">
				<a href="/block/onlajn-biblioteka" class="content-nav__item">
					<?= $library ?>
					<img src="/templates/ksu/img/icons/header/job.svg" alt="Портал">
				</a>
			</div>
			<div class="col-lg-3 col-md-6 col-sm-6">
				<a href="http://portal.ksu.edu.kz/rector_blog/" target="_blank" class="content-nav__item">
					<?= $rector_blog ?>
					<img src="/templates/ksu/img/icons/header/blog.svg" alt="Портал">
				</a>
			</div>
		</div>
		<div class="row">
			<div class="col-lg-3 col-md-6 col-sm-6">
				<a class="content-nav__item" data-fancybox data-src="#covidModal" href="javascript:;">
					Covid-19
					<img src="/templates/ksu/img/icons/header/portal.svg" alt="Портал">
				</a>
			</div>
		</div>
	</div>
	</div>
</section>
<div class="spok">
	<p>&nbsp;</p>
</div>
<section id="sec-menu">
	<a>
		<h3><?= $regional ?></h3>
		<img src="/templates/ksu/img/innovation.png" alt="">
	</a>
	<a data-fancybox data-src="#engineerModal" href="javascript:;">
		<h3><?= $engineering ?></h3>
		<img src="/templates/ksu/img/sec-mnu1.png" alt="">
	</a>
	<a>
		<h3><?= $biotechnology ?></br></h3>
		<img src="/templates/ksu/img/sec-mnu2.png" alt="">
	</a>
</section>
<div class="infographic">
	<div class="container">
		<div class="row">
			<div class="col-lg-3">
				<div class="infographic__item">
					<div class="infographic__number">
						109
					</div>
					<div class="infographic__text">
					<?= $educational_programs ?>
					</div>
				</div>
			</div>
			<div class="col-lg-3">
				<div class="infographic__item">
					<div class="infographic__number">
						4454
					</div>
					<div class="infographic__text">
					<?= $number_students ?>
					</div>
				</div>
			</div>
			<div class="col-lg-3">
				<div class="infographic__item">
					<div class="infographic__number">
						456
					</div>
					<div class="infographic__text">
					<?= $teaching_staff ?>
					</div>
				</div>
			</div>
			<div class="col-lg-3">
				<div class="infographic__item">
					<div class="infographic__number">
						182
					</div>
					<div class="infographic__text">
						<?= $teachers_with_academic ?>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
<div class="container">
	<div class="news-feed">
		<div class="row">
			<div class="col-lg-6">
				<div class="news-feed__guests">
					<div class="news-feed__title">
						<?= $guests ?>
					</div>
					<?= $this->render($this->macros('news', 'lastlist', array('guests', null, null, true)), 'news/guests'); ?>
				</div>
			</div>
			<div class="col-lg-6">
				<div class="news-feed__interview">
					<div class="news-feed__title">
						<?= $interview ?>
					</div>
					<?= $this->render($this->macros('news', 'lastlist', array('interviews_and_analytics', null, null, true)), 'news/analytics'); ?>
				</div>
			</div>
		</div>
	</div>
</div>
<div style="display: none;" class="covid-modal" id="covidModal">
	<ul class="covid-modal-list">
		<li class="covid-modal-list__item covid-modal-list__item--1">
			Covid-19
		</li>
		<li class="covid-modal-list__item covid-modal-list__item--2">
			Симптомы
		</li>
		<li class="covid-modal-list__item covid-modal-list__item--3">
			Профилактика
		</li>
	</ul>
	<div class="covid-modal__content">
		<div class="covid active">
			<div class="covid__title">Оповещение о COVID-19</div>
			<h3>Что такое коронавирус?</h3>
			<p>Коронавирусы — это большое семейство вирусов, которые приводят к заболеваниям органов дыхания. Чаще всего — без тяжёлых симптомов. Всего насчитывается около 40 видов коронавируса. Пандемию вызвал SARS-CoV-2, который впервые был обнаружен в Китае в конце декабря.</p>
			<p>Считается, что инкубационный период нового коронавируса — до 14 дней. Всё это время человек может быть носителем вируса, но не подозревать об этом. Именно поэтому стоит соблюдать двухнедельный карантин, если вы вернулись из страны, где много случаев заражения, или контактировали с заболевшим.</p>
			<h3>Как распространяется новый коронавирус?</h3>
			<p>Коронавирус передаётся от человека к человеку при близком контакте с больным — чаще всего с такими симптомами, как кашель и чихание. Учёные продолжают исследовать, как долго вирус может сохранять жизнеспособность на предметах. Однако речь про небольшие промежутки времени — так что письма и посылки не опасны для людей.</p>
		</div>
		<div class="symptoms">
			<h3>Первичные симптомы</h3>
			<div class="symptoms-item">
				<div class="symptoms-item__img">
					<img src="templates/ksu/img/window/covid/icon/1.svg" alt="">
				</div>
				<div class="symptoms-item__title">
					Насморк
				</div>
			</div>
			<div class="symptoms-item">
				<div class="symptoms-item__img">
					<img src="templates/ksu/img/window/covid/icon/cough.svg" alt="">
				</div>
				<div class="symptoms-item__title">
					Сухой кашель
				</div>
			</div>
			<div class="symptoms-item">
				<div class="symptoms-item__img">
					<img src="templates/ksu/img/window/covid/icon/sore-throat.svg" alt="">
				</div>
				<div class="symptoms-item__title">
					Боль в горле
				</div>
			</div>
			<h3>Вторичные симптомы</h3>
			<div class="symptoms-item">
				<div class="symptoms-item__img">
					<img src="templates/ksu/img/window/covid/icon/symptoms.svg" alt="">
				</div>
				<div class="symptoms-item__title">
					Температура
				</div>
			</div>
			<div class="symptoms-item">
				<div class="symptoms-item__img">
					<img src="templates/ksu/img/window/covid/icon/pneumonia.svg" alt="">
				</div>
				<div class="symptoms-item__title">
					Пневмания
				</div>
			</div>
			<div class="symptoms-item">
				<div class="symptoms-item__img">
					<img src="templates/ksu/img/window/covid/icon/breath.svg" alt="">
				</div>
				<div class="symptoms-item__title">
					Удушение
				</div>
			</div>
			<p>Если вы обнаружили у себя похожие симптомы — вызовите врача. Это не значит, что у вас вирус, но будет полезным провериться.</p>
			<p>Если в течение последних двух недель вы посещали страны, где зафиксировано много случаев коронавирусной инфекции, или контактировали с кем-то, кто был в таких странах, к симптомам стоит отнестись максимально внимательно. Не стоит идти в больницу или поликлинику — высок риск заразить окружающих.</p>
		</div>
		<div class="prevention">
			<h3>7 шагов по профилактике коронавирусной инфекции</h3>
			<ul>
				<li>Воздержитесь от посещения общественных мест: торговых центров, спортивных и зрелищных мероприятий, транспорта в час пик.</li>
				<li>Не касайтесь грязными руками глаз, лица и рта.</li>
				<li>Избегайте близких контактов и пребывания в одном помещении с людьми, имеющими видимые признаки ОРВИ (кашель, чихание, выделения из носа).</li>
				<li>Мойте руки с мылом и водой тщательно после возвращения с улицы, контактов с посторонними людьми.</li>
				<li>Дезинфицируйте гаджеты, оргтехнику и поверхности, к которым прикасаетесь.</li>
				<li>Ограничьте по возможности при приветствии тесные объятия и рукопожатия.</li>
				<li>Пользуйтесь только индивидуальными предметами личной гигиены (полотенце, зубная щетка).</li>
			</ul>
			<h3 class="prevention__next">Какие меры по профилактике коронавируса существуют?</h3>
			<p>Самое важное, что можно сделать, чтобы защитить себя, – это соблюдать правила личной гигиены и сократить посещения общественных и людных мест.</p>
			<ul>
				<li>Держите руки в чистоте, часто мойте их водой с мылом или используйте дезинфицирующее средство.</li>
				<li>Старайтесь не касаться рта, носа или глаз немытыми руками (обычно такие прикосновения неосознанно совершаются нами в среднем 15 раз в час).</li>
				<li>Старайтесь не касаться рта, носа или глаз немытыми руками (обычно такие прикосновения неосознанно совершаются нами в среднем 15 раз в час).</li>
				<li>На работе регулярно очищайте поверхности и устройства, к которым вы прикасаетесь (клавиатура компьютера, панели оргтехники общего использования, экран смартфона, пульты, дверные ручки и поручни).</li>
				<li>Носите с собой одноразовые салфетки и всегда прикрывайте нос и рот, когда вы кашляете или чихаете.</li>
				<li>Не ешьте еду (орешки, чипсы, печенье и другие снеки) из общих упаковок или посуды, если другие люди погружали в них свои пальцы.</li>
				<li>Объясните детям, как распространяются микробы и почему важна хорошая гигиена рук и лица. Расскажите детям о профилактике коронавируса.</li>
				<li>Часто проветривайте помещения.</li>
				<li>По возможности, соблюдайте дистанцию не менее 1 метра при общении с коллегами, друзьями, родными и близкими</li>
			</ul>
		</div>
	</div>
</div>
<a data-fancybox data-src="#covidModal" href="javascript:;" id="covid-modal"></a>
<!---------------- Футер ---------------->
<? include 'footer.phtml'; ?>
