<!---------------- Модальное окна ---------------->
	<div style="display: none;" id="callModal" class="call-modal">
	<div class="call-modal__logo"><img src="/templates/ksu/img/window/logo.png" alt="KSU"></div>
	<div class="call-modal__bg-top"><img src="/templates/ksu/img/window/bg-top.png" alt="elem1"></div>
	<ul class="call-modal__list">
		<li>В целях оперативного решения вопросов по обучению в дистанционном формате необходимо обращаться в Call-центр: <a href="tel:87142931010">8(7142)93-10-10</a></li>
		<li>Центр методологической поддержки: <a href="tel:87142511120">8(7142)51-11-20</a></li>
		<li>Центр технической поддержки: <a href="tel:87142390190">8(7142)39-01-90</a></li>
		<li>В целях оперативного решения вопросов по учебной работе: <a href="tel:87142511100">8(7142)51-11-00</a></li>
		<li>По вопросам дистанционного обучения: <a href="tel:87142390630">8(7142)39-06-30</a></li>
		<li>Центр психологической поддержки и инклюзивного образования:  <a href="tel:87772760674">8(777)276-06-74</a></li>
	</ul>
	<div class="call-modal__link">
		<a href="https://www.facebook.com/%D0%9A%D0%93%D0%A3-%D0%B8%D0%BC%D0%B5%D0%BD%D0%B8-%D0%90%D1%85%D0%BC%D0%B5%D1%82%D0%B0-%D0%91%D0%B0%D0%B9%D1%82%D1%83%D1%80%D1%81%D1%8B%D0%BD%D0%BE%D0%B2%D0%B0-%D0%98%D0%BD%D1%81%D1%82%D0%B8%D1%82%D1%83%D1%82-%D0%B4%D0%B8%D1%81%D1%82%D0%B0%D0%BD%D1%86%D0%B8%D0%BE%D0%BD%D0%BD%D0%BE%D0%B3%D0%BE-%D0%BE%D0%B1%D1%83%D1%87%D0%B5%D0%BD%D0%B8%D1%8F-%D0%B8-%D0%9F%D0%A0-100112951376605/?ti=as" target="_blank"><img src="/templates/ksu/img/window/002-facebook.svg" alt="facebook"></a>
		<a href="https://www.instagram.com/institut_kgu/?igshid=odfce469ty7r" target="_blank"><img src="/templates/ksu/img/window/001-instagram.svg" alt="instagram"></a>
	</div>
	<div class="call-modal__bg-bottom"><img src="/templates/ksu/img/window/bg-bottom.png" alt="elem2"></div>
</div>
	<div style="display: none;" id="engineerModal" class="video-engineer">
		<iframe width="100%" height="100%" src="https://www.youtube.com/embed/y8q580Ymj2A" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
	</div>
	<div class="modal-search"></div>
	<div class="modal-search_wrapper">
		<form class="modal-search_inner" action="search_result" method="GET" >
			<img src="/templates/ksu/img/icons/search.svg" class="modal-search_img" alt="Поиск">
			<input type="search" name="search" placeholder="Поиск..." class="modal-search_input">
			<div class="modal-search_close">
				<span></span>
				<span></span>
			</div>
	  </form>
	</div>
	<footer class="footer">
		<img src="/templates/ksu/img/footer-ksu.png" alt="KSU" class="footer__img">
		<div class="footer__text"><?= $footer_kgu ?></div>
	</footer>
  <script src="/templates/ksu/js/jquery.min.js"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-cookie/1.4.1/jquery.cookie.min.js"></script>
	<script src="/templates/ksu/libs/webticker/jquery.webticker.min.js"></script>
	<script src="/templates/ksu/libs/owl-carousel/owl.carousel.min.js"></script>
  <script src="/templates/ksu/libs/fancybox/jquery.fancybox.min.js"></script>
	<script src="/templates/ksu/js/scripts.min.js?<?echo $js_version?>"></script>
	<script src="/templates/ksu/js/common.js?<?echo $js_version?>"></script>
	<script type="text/javascript">
		function covid() {
			$("#covid-modal").click();
			$.cookie('covid', 'true', { expires: 1, path: '/' });
		}
		if ( $.cookie('covid') == null ) {
		  setTimeout(covid, 500);
		}
	</script>
  <!-- Global site tag (gtag.js) - Google Analytics -->
  <script async src="https://www.googletagmanager.com/gtag/js?id=UA-158283481-1"></script>
  <script>
    window.dataLayer = window.dataLayer || [];
    function gtag(){dataLayer.push(arguments);}
    gtag('js', new Date());

    gtag('config', 'UA-158283481-1');
  </script>
  <!-- Yandex.Metrika counter -->
  <script type="text/javascript" >
     (function(m,e,t,r,i,k,a){m[i]=m[i]||function(){(m[i].a=m[i].a||[]).push(arguments)};
     m[i].l=1*new Date();k=e.createElement(t),a=e.getElementsByTagName(t)[0],k.async=1,k.src=r,a.parentNode.insertBefore(k,a)})
     (window, document, "script", "https://mc.yandex.ru/metrika/tag.js", "ym");

     ym(57175126, "init", {
          clickmap:true,
          trackLinks:true,
          accurateTrackBounce:true,
          webvisor:true
     });
  </script>
  <noscript><div><img src="https://mc.yandex.ru/watch/57175126" style="position:absolute; left:-9999px;" alt="" /></div></noscript>
  <!-- /Yandex.Metrika counter -->
  <script src="https://ats.kts.kz/api/public.php?method=get-user-callback-form&companyId=4786&elemId=el-129600697"></script>
</body>
</html>
