<?
$abitur="Абитуриенту";
$voennaya="Военная кафедра";
$grant="Гранты и скидки";
$our="Наши выпускники";
$blockrektor="Блог ректора";
$kabinet="Личный кабинет";
$student="Cтудента / магистранта";
$teacher="Преподавателя";
$adviser="Эдвайзера";
$regional="SMART-центр";
$engineering="Инжиниринговый центр";
$biotechnology="НИИ прикладной биотехнологии";
$interview="Интервью и аналитика";
$guests="Гости университета";
$educational_programs="Pеализуемых образовательных программ";
$number_students="Kонтингент студентов";
$teaching_staff="Профессорско-преподавательский состав";
$teachers_with_academic ="Преподавателей с учеными степенями и званиями";
$footer_kgu="© 2020 КГУ имени А.Байтурсынова";
$blockportal="Портал";
$anti_portal="Антикоррупционный портал";
$internal_portal="Внутренний портал";
$nurly_zher="Нурлы жер";
$rector_blog="Блог ректора";
$library="Online Библиотека";
$blocktimetable="Расписание";
$dot="Дистанционное образование";

?>