<?
$abitur="Талапкерге";
$voennaya="Әскери кафедра";
$grant="Гранттар, жеңілдіктер, жатақхана";
$our="Біздің түлектер";
$blockrektor="Ректор блогы";
$kabinet="Жеке кабинет";
$student="Студенттің / магистранттың ";
$teacher="Оқытушының ";
$adviser="Эдвайзердің ";
$regional="SMART-орталығы";
$engineering="Инжинирингтік орталығы";
$biotechnology="Қолданбалы биотехнология ҒЗИ";
$interview="Сұхбат және аналитика";
$guests="Университет қонақтары";
$educational_programs="Іске асырылатын білім беру бағдарламалары";
$number_students="Студенттер контингенті";
$teaching_staff="Профессор-оқытушылар құрамы";
$teachers_with_academic="Ғылыми дәрежесі және атағы бар оқытушылар";
$footer_kgu="© 2020 Ахмет Байтұрсынов атындағы Университет";
$blockportal="Портал";
$anti_portal="Сыбайлас жемқорлық портал";
$internal_portal="Ішкі портал";
$nurly_zher="Нұрлы жер";
$rector_blog="Ректор блогы";
$blocktimetable="Кесте";
$library="Online Кітапхана";
$dot="Қашықтықтан оқыту";

?>